# Generated by Django 4.2.7 on 2023-11-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='data'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='hora'),
        ),
    ]
